# -*- coding: utf-8 -*-
"""CodeSoft_Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n67DTM_OGdDXezqe62Yyf03C59YNDppj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer


movies_data = pd.read_csv('IMDB.csv', encoding='latin1')


movies_data['Duration'] = movies_data['Duration'].str.extract('(\d+)').astype(float)
movies_data['Votes'] = movies_data['Votes'].str.replace(',', '')
movies_data['Votes'] = movies_data['Votes'].str.replace('M', 'e6').str.replace('k', 'e3')
movies_data['Votes'] = pd.to_numeric(movies_data['Votes'], errors='coerce')


movies_data = pd.concat([movies_data, movies_data['Genre'].str.get_dummies(sep=', ')], axis=1)
movies_data.drop(columns=['Genre'], inplace=True)


features = ['Year', 'Duration', 'Votes', 'Drama', 'Romance']
X = movies_data[features]
y = movies_data['Rating']


movies_data.dropna(subset=['Rating'], inplace=True)
X = movies_data[features]
y = movies_data['Rating']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)


model = LinearRegression()
model.fit(X_train_imputed, y_train)

train_score = model.score(X_train_imputed, y_train)
test_score = model.score(X_test_imputed, y_test)

print("Training Score:", train_score)
print("Testing Score:", test_score)